services:
  oem-setup:
    profiles: ["setup"]
    image: alpine/curl
    volumes:
      - ./oem:/oem
      - ./templates:/templates:ro
    environment:
      - REMOTE_KEY=${REMOTE_KEY}
      - VERSION=${VERSION}
    command:
      - /bin/sh
      - /templates/oem-setup.sh
    restart: "no"
  
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "xp"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 127.0.0.1:8006:8006
      - 127.0.0.1:3389:3389/tcp
      - 127.0.0.1:3389:3389/udp
    volumes:
      - ./windows:/storage
      - ./oem:/oem
    restart: always
    stop_grace_period: 2m
